"""Static HTML report generation.

Produces a small, fully self-contained website (no external CDNs or JS
libraries) for browsing the dives and their DSSG.  Charts are rendered as
inline SVG generated in Python so the report works completely offline.
"""

from __future__ import annotations

import html
import json
import os
from datetime import datetime

from .buhlmann import N2_HALFTIMES, N_COMPARTMENTS
from .calculator import DSSGResult
from .parser import Dive
from .risk import (DAN_DSL_2024_TABLE, PAPER_MEAN_DSSG, PAPER_MEDIAN_DCS,
                   PAPER_MEDIAN_NON_DCS, PAPER_SD_DSSG, classify)
from .statistics_report import DiveSummary

CSS = """
:root {
  --bg: #0e1726; --panel: #16223a; --panel2: #1d2c49; --ink: #e8eef7;
  --muted: #9fb0c8; --accent: #38bdf8; --accent2: #f472b6; --good: #34d399;
  --warn: #fbbf24; --bad: #f87171; --line: #2a3a5c;
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink);
  font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.wrap { max-width: 1080px; margin: 0 auto; padding: 28px 20px 64px; }
header h1 { margin: 0 0 4px; font-size: 26px; }
header .sub { color: var(--muted); margin-bottom: 24px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 14px; margin: 18px 0 28px; }
.card { background: var(--panel); border: 1px solid var(--line); border-radius: 12px;
  padding: 16px 18px; }
.card .k { color: var(--muted); font-size: 12px; text-transform: uppercase;
  letter-spacing: .04em; }
.card .v { font-size: 24px; font-weight: 600; margin-top: 4px; }
.card .v small { font-size: 13px; color: var(--muted); font-weight: 400; }
.panel { background: var(--panel); border: 1px solid var(--line); border-radius: 12px;
  padding: 18px 20px; margin: 18px 0; }
h2 { font-size: 18px; margin: 8px 0 14px; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
th, td { text-align: left; padding: 9px 10px; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-weight: 600; cursor: pointer; user-select: none;
  white-space: nowrap; }
th.num, td.num { text-align: right; }
tbody tr:hover { background: var(--panel2); }
.bar { height: 8px; border-radius: 4px; background: var(--accent);
  display: inline-block; vertical-align: middle; }
.pill { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 12px; }
.dot { display: inline-block; width: 9px; height: 9px; border-radius: 50%;
  margin-right: 6px; vertical-align: middle; }
.muted { color: var(--muted); }
.method { color: var(--muted); font-size: 13.5px; }
.method code { background: var(--panel2); padding: 1px 5px; border-radius: 4px; }
footer { color: var(--muted); font-size: 12px; margin-top: 32px; text-align: center; }
.grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
@media (max-width: 760px) { .grid2 { grid-template-columns: 1fr; } }
svg { max-width: 100%; height: auto; }
"""

SORT_JS = """
function sortTable(table, col, numeric) {
  const tbody = table.tBodies[0];
  const rows = Array.from(tbody.rows);
  const dir = table.getAttribute('data-dir-' + col) === 'asc' ? -1 : 1;
  table.setAttribute('data-dir-' + col, dir === 1 ? 'asc' : 'desc');
  rows.sort((a, b) => {
    let x = a.cells[col].getAttribute('data-v') ?? a.cells[col].innerText;
    let y = b.cells[col].getAttribute('data-v') ?? b.cells[col].innerText;
    if (numeric) { x = parseFloat(x) || 0; y = parseFloat(y) || 0; return (x - y) * dir; }
    return x.localeCompare(y) * dir;
  });
  rows.forEach(r => tbody.appendChild(r));
}
document.querySelectorAll('table.sortable').forEach(t => {
  Array.from(t.tHead.rows[0].cells).forEach((th, i) => {
    th.addEventListener('click', () => sortTable(t, i, th.classList.contains('num')));
  });
});
"""


def _esc(value) -> str:
    return html.escape(str(value)) if value is not None else ""


def _page(title: str, body: str, extra_js: str = "") -> str:
    js = f"<script>{SORT_JS}{extra_js}</script>" if (SORT_JS or extra_js) else ""
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{_esc(title)}</title><style>{CSS}</style></head>"
        f"<body><div class='wrap'>{body}"
        "<footer>Generated by the MacDive DSSG calculator &middot; "
        "DSSG = DAN Surface Supersaturation Gradient (Buhlmann ZH-L16)</footer>"
        f"</div>{js}</body></html>"
    )


# --------------------------------------------------------------------------- #
# SVG chart helpers
# --------------------------------------------------------------------------- #

def _svg_depth_profile(samples, max_depth: float, duration_s: float,
                       width: int = 640, height: int = 240) -> str:
    pad_l, pad_r, pad_t, pad_b = 44, 14, 14, 28
    w = width - pad_l - pad_r
    h = height - pad_t - pad_b
    dur = max(duration_s, 1.0)
    dmax = max(max_depth, 1.0)

    def x(t):
        return pad_l + (t / dur) * w

    def y(d):
        return pad_t + (d / dmax) * h

    pts = " ".join(f"{x(s.time_s):.1f},{y(s.depth_m):.1f}" for s in samples)
    area = f"{x(0):.1f},{y(0):.1f} " + pts + f" {x(samples[-1].time_s):.1f},{y(0):.1f}"

    grid = []
    for frac in (0.25, 0.5, 0.75, 1.0):
        yy = pad_t + frac * h
        grid.append(f"<line x1='{pad_l}' y1='{yy:.0f}' x2='{pad_l + w}' y2='{yy:.0f}' "
                    f"stroke='#2a3a5c' stroke-width='1'/>")
        grid.append(f"<text x='{pad_l - 6}' y='{yy + 4:.0f}' fill='#9fb0c8' "
                    f"font-size='10' text-anchor='end'>{dmax * frac:.0f}m</text>")
    for frac in (0.0, 0.5, 1.0):
        xx = pad_l + frac * w
        grid.append(f"<text x='{xx:.0f}' y='{height - 8}' fill='#9fb0c8' "
                    f"font-size='10' text-anchor='middle'>{dur / 60 * frac:.0f}min</text>")

    return (
        f"<svg viewBox='0 0 {width} {height}' role='img' aria-label='Depth profile'>"
        f"{''.join(grid)}"
        f"<polygon points='{area}' fill='#38bdf833'/>"
        f"<polyline points='{pts}' fill='none' stroke='#38bdf8' stroke-width='2'/>"
        f"</svg>"
    )


def _svg_compartment_bars(gradients: list[float], leading: int,
                          width: int = 640, height: int = 260) -> str:
    pad_l, pad_r, pad_t, pad_b = 40, 14, 14, 40
    w = width - pad_l - pad_r
    h = height - pad_t - pad_b
    n = len(gradients)
    gmax = max(max(gradients), 0.01)
    gmin = min(min(gradients), 0.0)
    span = gmax - gmin or 1.0
    bw = w / n * 0.7
    gap = w / n

    def y(v):
        return pad_t + (gmax - v) / span * h

    zero_y = y(0.0)
    bars = [f"<line x1='{pad_l}' y1='{zero_y:.1f}' x2='{pad_l + w}' y2='{zero_y:.1f}' "
            f"stroke='#9fb0c8' stroke-width='1' stroke-dasharray='3 3'/>"]
    for i, g in enumerate(gradients):
        cx = pad_l + i * gap + (gap - bw) / 2
        top = y(max(g, 0.0))
        bottom = y(min(g, 0.0))
        colour = "#f472b6" if (i + 1) == leading else ("#34d399" if g > 0 else "#9fb0c8")
        bars.append(
            f"<rect x='{cx:.1f}' y='{top:.1f}' width='{bw:.1f}' "
            f"height='{max(bottom - top, 1):.1f}' fill='{colour}' rx='2'>"
            f"<title>Compartment {i + 1} ({N2_HALFTIMES[i]:.1f} min N2): "
            f"{g * 10:.2f} msw</title></rect>"
        )
        bars.append(f"<text x='{cx + bw / 2:.1f}' y='{height - 24}' fill='#9fb0c8' "
                    f"font-size='9' text-anchor='middle'>{i + 1}</text>")
    bars.append(f"<text x='{pad_l + w / 2:.0f}' y='{height - 6}' fill='#9fb0c8' "
                f"font-size='11' text-anchor='middle'>Tissue compartment "
                f"(fast &rarr; slow)</text>")
    return (
        f"<svg viewBox='0 0 {width} {height}' role='img' "
        f"aria-label='Per-compartment surface supersaturation gradient'>"
        f"{''.join(bars)}</svg>"
    )


def _svg_histogram(hist: dict, width: int = 640, height: int = 220,
                   unit_label: str = "DSSG (bar/ata)") -> str:
    edges = hist.get("edges", [])
    counts = hist.get("counts", [])
    if not counts:
        return "<p class='muted'>Not enough data for a histogram.</p>"
    pad_l, pad_r, pad_t, pad_b = 36, 14, 14, 36
    w = width - pad_l - pad_r
    h = height - pad_t - pad_b
    n = len(counts)
    cmax = max(counts) or 1
    bw = w / n * 0.8
    gap = w / n
    bars = []
    for i, c in enumerate(counts):
        bh = (c / cmax) * h
        cx = pad_l + i * gap + (gap - bw) / 2
        cy = pad_t + h - bh
        bars.append(f"<rect x='{cx:.1f}' y='{cy:.1f}' width='{bw:.1f}' "
                    f"height='{bh:.1f}' fill='#38bdf8' rx='2'><title>"
                    f"{edges[i]:.1f}–{edges[i + 1]:.1f} msw: {c} dives</title></rect>")
        bars.append(f"<text x='{cx + bw / 2:.1f}' y='{cy - 4:.1f}' fill='#e8eef7' "
                    f"font-size='10' text-anchor='middle'>{c if c else ''}</text>")
    for i in (0, n // 2, n):
        xx = pad_l + i * gap
        val = edges[i] if i < len(edges) else edges[-1]
        bars.append(f"<text x='{xx:.0f}' y='{height - 6}' fill='#9fb0c8' "
                    f"font-size='10' text-anchor='middle'>{val:.1f}</text>")
    bars.append(f"<text x='{pad_l + w / 2:.0f}' y='{height - 20}' fill='#9fb0c8' "
                f"font-size='11' text-anchor='middle'>{unit_label}</text>")
    return (f"<svg viewBox='0 0 {width} {height}' role='img' "
            f"aria-label='DSSG distribution'>{''.join(bars)}</svg>")


# --------------------------------------------------------------------------- #
# Page builders
# --------------------------------------------------------------------------- #

def _dssg_pill(dssg_bar: float) -> str:
    """Coloured DSSG value, banded by the DAN DSL 2024 empirical risk."""
    band = classify(dssg_bar)
    c = band.colour
    return (f"<span class='pill' title='{band.label} risk &middot; "
            f"~{band.dcs_rate_pct:.3g}% observed DCS rate' "
            f"style='background:{c}22;color:{c};border:1px solid {c}77'>"
            f"{dssg_bar:.2f}</span>")


def render_index(summaries: list[DiveSummary], stats: dict) -> str:
    d = stats.get("dssg", {})
    cards = [
        ("Dives analysed", f"{stats.get('dive_count', 0)}", ""),
        ("Mean DSSG", f"{d.get('mean', 0):.2f}", " bar"),
        ("Max DSSG", f"{d.get('max', 0):.2f}", " bar"),
        ("Median DSSG", f"{d.get('median', 0):.2f}", " bar"),
    ]
    cards_html = "".join(
        f"<div class='card'><div class='k'>{_esc(k)}</div>"
        f"<div class='v'>{_esc(v)}<small>{_esc(u)}</small></div></div>"
        for k, v, u in cards
    )

    max_dssg = max((s.dssg for s in summaries), default=1.0) or 1.0
    rows = []
    for s in summaries:
        date = s.date[:10] if s.date else "—"
        barw = max(2, int(s.dssg / max_dssg * 80))
        rate = "0" if s.dcs_rate_pct == 0 else f"{s.dcs_rate_pct:.3g}%"
        rows.append(
            "<tr>"
            f"<td class='num' data-v='{s.number}'>"
            f"<a href='dive_{s.number}.html'>{s.number}</a></td>"
            f"<td data-v='{_esc(s.date or '')}'>{_esc(date)}</td>"
            f"<td>{_esc(s.location or '—')}</td>"
            f"<td class='num' data-v='{s.max_depth_m}'>{s.max_depth_m:.1f}</td>"
            f"<td class='num' data-v='{s.duration_min}'>{s.duration_min:.0f}</td>"
            f"<td class='num' data-v='{s.dssg}'>{_dssg_pill(s.dssg)} "
            f"<span class='bar' style='width:{barw}px'></span></td>"
            f"<td data-v='{_esc(s.risk_band)}'>{_esc(s.risk_band)}</td>"
            f"<td class='num' data-v='{s.dcs_rate_pct}'>{rate}</td>"
            f"<td class='num' data-v='{s.leading_compartment}'>#{s.leading_compartment}</td>"
            "</tr>"
        )

    table = (
        "<table class='sortable'><thead><tr>"
        "<th class='num'>#</th><th>Date</th><th>Location</th>"
        "<th class='num'>Max depth (m)</th><th class='num'>Duration (min)</th>"
        "<th class='num'>DSSG</th><th>Risk</th>"
        "<th class='num'>DCS rate</th><th class='num'>Leading comp.</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
    )

    leading_freq = stats.get("leading_compartment_frequency", {})
    leading_html = ", ".join(
        f"#{k}&nbsp;({v})" for k, v in leading_freq.items()
    ) or "&mdash;"

    corr_depth = stats.get("correlation_depth_vs_dssg")
    corr_dur = stats.get("correlation_duration_vs_dssg")
    expected = stats.get("expected_dcs_dives", 0)

    # DAN DSL 2024 empirical risk reference table.
    risk_rows = "".join(
        f"<tr><td>{_esc(label)}</td>"
        f"<td class='num'><span class='dot' style='background:"
        f"{classify(_band_value(label)).colour}'></span>"
        f"{_esc(classify(_band_value(label)).label)}</td>"
        f"<td class='num'>{rate:.3g}%</td></tr>"
        for label, rate in DAN_DSL_2024_TABLE
    )
    risk_table = (
        "<table><thead><tr><th>DSSG (bar/ata)</th><th class='num'>Risk band</th>"
        "<th class='num'>Observed DCS rate</th></tr></thead><tbody>"
        + risk_rows + "</tbody></table>"
    )

    body = (
        "<header><h1>MacDive DSSG report</h1>"
        f"<div class='sub'>DAN Surface Supersaturation Gradients across "
        f"{stats.get('dive_count', 0)} dives &middot; generated "
        f"{datetime.now():%Y-%m-%d %H:%M}</div></header>"
        f"<div class='cards'>{cards_html}</div>"
        "<div class='grid2'>"
        "<div class='panel'><h2>DSSG distribution</h2>"
        f"{_svg_histogram(stats.get('dssg_histogram', {}))}"
        f"<p class='muted' style='margin-top:10px'>Reference (DAN DSL 2024): "
        f"mean DSSG <b>{PAPER_MEAN_DSSG:.2f} &plusmn; {PAPER_SD_DSSG:.2f}</b>; "
        f"median <b>{PAPER_MEDIAN_NON_DCS:.3f}</b> (no DCS) vs "
        f"<b>{PAPER_MEDIAN_DCS:.3f}</b> (DCS).</p></div>"
        "<div class='panel'><h2>Overview</h2>"
        f"<p class='muted'>Std deviation: <b>{d.get('stdev', 0):.2f} bar</b><br>"
        f"Range: <b>{d.get('min', 0):.2f}</b> &ndash; <b>{d.get('max', 0):.2f} bar</b><br>"
        f"Leading compartments: {leading_html}<br>"
        f"Expected DCS dives (sum of band rates): <b>{expected:.2f}</b><br>"
        f"Corr. depth vs DSSG: <b>{_fmt(corr_depth)}</b><br>"
        f"Corr. duration vs DSSG: <b>{_fmt(corr_dur)}</b></p></div>"
        "</div>"
        f"<div class='panel'><h2>Dives</h2>"
        "<p class='muted'>Click a column header to sort. Click a dive number "
        "for the full profile and per-compartment breakdown. The DSSG value is "
        "in bar/ata; colours follow the DAN DSL 2024 risk bands.</p>"
        f"{table}</div>"
        "<div class='grid2'>"
        "<div class='panel'><h2>DCS risk by DSSG (DAN DSL 2024)</h2>"
        f"{risk_table}</div>"
        "<div class='panel method'><h2>What is the DSSG?</h2>"
        "<p>The <b>DAN Surface Supersaturation Gradient</b> estimates the "
        "decompression stress a diver carries to the surface. A B&uuml;hlmann "
        "<b>ZH-L16C</b> model tracks dissolved nitrogen and helium in 16 tissue "
        "compartments through the recorded profile. At surfacing, each "
        "compartment's gradient is "
        "<code>tissue tension &minus; surface pressure</code>; the DSSG is the "
        "gradient of the <b>leading compartment</b> (highest critical ratio at "
        "surfacing), reported in bar/ata. In the DAN DSL 2024 study (127,957 "
        "dives) it was the strongest independent predictor of DCS.</p>"
        "<p style='font-size:12px'>Source: Marroni A. et al., "
        "<i>Identification of DCS risk factors in recreational diving: "
        "multifactorial model based on the DAN DSL Database 2024</i>, "
        "Int. Maritime Health, 2026. Educational tool &mdash; not a dive "
        "planner or medical device.</p>"
        "</div></div>"
    )
    return _page("MacDive DSSG report", body)


def _band_value(label: str) -> float:
    """Representative DSSG value for a Table-3 row label (for colour lookup)."""
    digits = "".join(ch for ch in label if (ch.isdigit() or ch == "."))
    return float(digits) if digits else 0.0


def render_dive(dive: Dive, result: DSSGResult, summary: DiveSummary) -> str:
    date = dive.datetime.strftime("%Y-%m-%d %H:%M") if dive.datetime else "Unknown date"
    gases = ", ".join(
        f"{m.name} (O2 {m.fo2 * 100:.0f}%"
        + (f", He {m.fhe * 100:.0f}%" if m.fhe else "") + ")"
        for m in dive.gas_mixes.values()
    ) or "Air (assumed)"
    temp = f"{dive.min_temp_c:.1f} &deg;C" if dive.min_temp_c is not None else "—"
    band = classify(result.dssg_bar)
    rate = "0" if band.dcs_rate_pct == 0 else f"{band.dcs_rate_pct:.3g}%"

    cards = [
        ("DSSG", f"{result.dssg_bar:.3f}", " bar/ata"),
        ("Risk band",
         f"<span class='dot' style='background:{band.colour}'></span>{band.label}",
         f" &middot; ~{rate} DCS"),
        ("Leading compartment", f"#{result.leading_compartment}",
         f" ({N2_HALFTIMES[result.leading_compartment - 1]:.1f} min)"),
        ("Max depth", f"{dive.max_depth:.1f}", " m"),
        ("Duration", f"{dive.duration_s / 60:.0f}", " min"),
        ("DSSG (msw)", f"{result.dssg_msw:.2f}", " msw"),
    ]
    cards_html = "".join(
        f"<div class='card'><div class='k'>{_esc(k)}</div>"
        f"<div class='v'>{v}<small>{u}</small></div></div>"
        for k, v, u in cards
    )

    body = (
        f"<header><h1>Dive #{dive.number}</h1>"
        f"<div class='sub'>{_esc(date)} &middot; "
        f"{_esc(dive.location or 'Unknown site')} &middot; "
        f"<a href='index.html'>&larr; back to all dives</a></div></header>"
        f"<div class='cards'>{cards_html}</div>"
        "<div class='panel'><h2>Depth profile</h2>"
        f"{_svg_depth_profile(dive.samples, dive.max_depth, dive.duration_s)}</div>"
        "<div class='panel'><h2>Surface supersaturation gradient by compartment</h2>"
        "<p class='muted'>Gradient = tissue tension &minus; surface pressure at "
        "surfacing. The pink bar is the leading compartment (highest critical "
        "ratio) that defines this dive's DSSG.</p>"
        f"{_svg_compartment_bars(result.surface_gradients, result.leading_compartment)}"
        "</div>"
        f"<div class='panel'><h2>Dive details</h2><table>"
        f"<tr><th>Gas mixes</th><td>{_esc(gases)}</td></tr>"
        f"<tr><th>Min temperature</th><td>{temp}</td></tr>"
        f"<tr><th>Surface pressure</th><td>{dive.surface_pressure:.4f} bar</td></tr>"
        f"<tr><th>Profile samples</th><td>{len(dive.samples)}</td></tr>"
        f"<tr><th>DSSG (leading compartment)</th>"
        f"<td>{result.dssg_bar:.3f} bar/ata "
        f"({result.dssg_msw:.2f} msw) &middot; compartment #"
        f"{result.leading_compartment}</td></tr>"
        f"<tr><th>Empirical DCS rate (DAN DSL 2024)</th>"
        f"<td><span class='dot' style='background:{band.colour}'></span>"
        f"{band.label} &middot; ~{rate}</td></tr>"
        "</table></div>"
    )
    return _page(f"Dive #{dive.number} – DSSG", body)


def _fmt(value) -> str:
    return f"{value:.2f}" if isinstance(value, (int, float)) else "—"


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #

def write_report(output_dir: str, dives, results, summaries, stats) -> None:
    os.makedirs(output_dir, exist_ok=True)

    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(render_index(summaries, stats))

    for dive, result, summary in zip(dives, results, summaries):
        page = render_dive(dive, result, summary)
        with open(os.path.join(output_dir, f"dive_{dive.number}.html"),
                  "w", encoding="utf-8") as fh:
            fh.write(page)

    with open(os.path.join(output_dir, "statistics.json"), "w", encoding="utf-8") as fh:
        json.dump(stats, fh, indent=2)
